# NAME: Andrew Choi
# EMAIL: asjchoi@ucla.edu
# ID: 205348339

.SILENT:

default: lab1b

lab1a:
	gcc -g -Wall -Wextra lab1b.c -o lab1b

clean:
	rm -rf lab1a lab1b-205348339.tar.gz

dist:
	tar -zcvf lab1b-205348339.tar.gz lab1b.c Makefile README
