.SILENT:

default: dist

clean:
	rm -rf lab4a-205348339.tar.gz

dist:
	tar -zcvf lab4a-205348339.tar.gz my_beaglebone.jpg connected.png \
									 copy.png build_run.png git.png \
	 								 Makefile README
