# NAME: Andrew Choi
# EMAIL: asjchoi@ucla.edu
# ID: 205348339

.SILENT:

default: lab2a

lab2a:
	gcc -g -Wall -Wextra lab2a.c -o lab2a

clean:
	rm -rf lab2a lab2a-205348339.tar.gz

dist:
	tar -zcvf lab2a-205348339.tar.gz lab2a.c Makefile README
